# Regresión lineal en Python
## El paquete scikit-learn para regresión lineal y la selección de rasgos.

In [1]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("../../../Machine Learning/python-ml-course-master/datasets/ads/Advertising.csv")

In [3]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [4]:
x = data[feature_cols] #Separo lo que serían las candidatas a ser las variables predictorias
y = data["Sales"] #Separo lo que sería la variable a predecir

In [107]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, 2, step=1)
selector = selector.fit(x,y)

C:\Users\kmurg\anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [108]:
selector.support_ #Si vemos en feautre_cols han quedado sólo true la variable TV y Radio, y False Newspaper. 

array([ True,  True, False])

In [109]:
selector.ranking_

array([1, 1, 2])

In [110]:
selector.n_features_

2

In [111]:
from sklearn.linear_model import LinearRegression

In [112]:
x_pred = x[["Radio", "TV"]]

In [113]:
lm = LinearRegression()
lm.fit(x_pred, y)

LinearRegression()

In [114]:
lm.intercept_

2.921099912405138

In [115]:
lm.coef_

array([0.18799423, 0.04575482])

In [116]:
lm.score(x_pred, y)

0.8971942610828956

In [117]:
sales_pred = lm.predict(pd.DataFrame(data[["Radio", "TV"]]))

In [118]:
SSD = sum((data["Sales"] - sales_pred)**2)
RSE = np.sqrt(SSD/(len(data)-1-1))
sales_mean = np.mean(data["Sales"])
error = RSE / sales_mean *100
error

11.960133193808245